2025-02-27 14:56:37,351 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:44915'
2025-02-27 14:56:37,391 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:42649'
2025-02-27 14:56:37,415 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:43475'
2025-02-27 14:56:37,451 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:46541'
2025-02-27 14:56:37,487 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:44849'
2025-02-27 14:56:37,523 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:37835'
2025-02-27 14:56:39,987 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:46119
2025-02-27 14:56:39,987 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:46119
2025-02-27 14:56:39,987 - distributed.worker - INFO -           Worker name:           SLURMCluster-7-2
2025-02-27 14:56:39,987 - distributed.worker - INFO -          dashboard at:          172.26.1.15:46061
2025-02-27 14:56:39,988 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,988 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,988 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,988 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,988 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-mu7ljvem
2025-02-27 14:56:39,988 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,028 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:37677
2025-02-27 14:56:40,028 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:37677
2025-02-27 14:56:40,028 - distributed.worker - INFO -           Worker name:           SLURMCluster-7-1
2025-02-27 14:56:40,028 - distributed.worker - INFO -          dashboard at:          172.26.1.15:41135
2025-02-27 14:56:40,028 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,028 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,028 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,028 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,028 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-o8nihw5e
2025-02-27 14:56:40,029 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,031 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:33441
2025-02-27 14:56:40,032 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:33441
2025-02-27 14:56:40,032 - distributed.worker - INFO -           Worker name:           SLURMCluster-7-5
2025-02-27 14:56:40,032 - distributed.worker - INFO -          dashboard at:          172.26.1.15:40793
2025-02-27 14:56:40,032 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,032 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,032 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,032 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,032 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-xn3x5h87
2025-02-27 14:56:40,032 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,071 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:44367
2025-02-27 14:56:40,071 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:44367
2025-02-27 14:56:40,071 - distributed.worker - INFO -           Worker name:           SLURMCluster-7-4
2025-02-27 14:56:40,071 - distributed.worker - INFO -          dashboard at:          172.26.1.15:36307
2025-02-27 14:56:40,071 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,071 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,071 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,071 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,071 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-ysnbusl0
2025-02-27 14:56:40,071 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,094 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:44623
2025-02-27 14:56:40,094 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:44623
2025-02-27 14:56:40,094 - distributed.worker - INFO -           Worker name:           SLURMCluster-7-3
2025-02-27 14:56:40,094 - distributed.worker - INFO -          dashboard at:          172.26.1.15:37703
2025-02-27 14:56:40,094 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,094 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,095 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,095 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,095 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-r9d46aq3
2025-02-27 14:56:40,095 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,287 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:38405
2025-02-27 14:56:40,288 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:38405
2025-02-27 14:56:40,288 - distributed.worker - INFO -           Worker name:           SLURMCluster-7-0
2025-02-27 14:56:40,288 - distributed.worker - INFO -          dashboard at:          172.26.1.15:44589
2025-02-27 14:56:40,288 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,288 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,288 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,288 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,288 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-m7ljs_2l
2025-02-27 14:56:40,288 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,696 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,697 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,697 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,705 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,706 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,706 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,707 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,720 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,730 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,731 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,731 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,739 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,754 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,754 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,754 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,770 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,770 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,770 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,771 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,779 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,984 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,985 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,985 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,995 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,704 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,705 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,705 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.69s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,705 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,717 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:02,116 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.06s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:35,744 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.87s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:43,656 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55210 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55222 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,856 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,856 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,857 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:44623. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:44367. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55188 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55198 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,857 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,858 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:37677. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:44915'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,858 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,859 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:33441. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55232 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,860 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:42649'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,860 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,861 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:38405. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,861 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:43475'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,861 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,863 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:46541'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55176 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,865 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:44849'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,864 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,865 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:46119. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,865 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,868 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:37835'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,868 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,904 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,905 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,906 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,907 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,915 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,916 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,933 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,939 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,939 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,940 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,951 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,951 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:43475'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,930 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:43475' closed.
2025-02-27 15:05:16,930 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:42649'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,930 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:42649' closed.
2025-02-27 15:05:16,981 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:37835'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,981 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:37835' closed.
2025-02-27 15:05:17,039 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:44915'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,039 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:44915' closed.
2025-02-27 15:05:17,273 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:44849'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,273 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:44849' closed.
2025-02-27 15:05:17,273 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:46541'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,273 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:46541' closed.
2025-02-27 15:05:17,274 - distributed.dask_worker - INFO - End worker
