2025-02-27 14:56:37,198 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:43189'
2025-02-27 14:56:37,203 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:39481'
2025-02-27 14:56:37,205 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:45119'
2025-02-27 14:56:37,213 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:38893'
2025-02-27 14:56:37,215 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:46849'
2025-02-27 14:56:37,217 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:37517'
2025-02-27 14:56:39,112 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:36055
2025-02-27 14:56:39,112 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:36055
2025-02-27 14:56:39,112 - distributed.worker - INFO -           Worker name:           SLURMCluster-5-4
2025-02-27 14:56:39,112 - distributed.worker - INFO -          dashboard at:          172.26.1.16:35797
2025-02-27 14:56:39,112 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,112 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,112 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,112 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,112 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-6e2e7qu9
2025-02-27 14:56:39,112 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,135 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:46639
2025-02-27 14:56:39,135 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:46639
2025-02-27 14:56:39,136 - distributed.worker - INFO -           Worker name:           SLURMCluster-5-1
2025-02-27 14:56:39,136 - distributed.worker - INFO -          dashboard at:          172.26.1.16:41987
2025-02-27 14:56:39,136 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,136 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,136 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,136 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,136 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-dd9f59tf
2025-02-27 14:56:39,136 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,244 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:36467
2025-02-27 14:56:39,244 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:36467
2025-02-27 14:56:39,244 - distributed.worker - INFO -           Worker name:           SLURMCluster-5-5
2025-02-27 14:56:39,244 - distributed.worker - INFO -          dashboard at:          172.26.1.16:39197
2025-02-27 14:56:39,244 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,244 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,244 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,244 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,244 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-8d7rrq6n
2025-02-27 14:56:39,244 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,259 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:46243
2025-02-27 14:56:39,259 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:46243
2025-02-27 14:56:39,260 - distributed.worker - INFO -           Worker name:           SLURMCluster-5-0
2025-02-27 14:56:39,260 - distributed.worker - INFO -          dashboard at:          172.26.1.16:35785
2025-02-27 14:56:39,260 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,260 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,260 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,261 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,261 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-z3wq7fkt
2025-02-27 14:56:39,261 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,266 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:35233
2025-02-27 14:56:39,267 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:35233
2025-02-27 14:56:39,267 - distributed.worker - INFO -           Worker name:           SLURMCluster-5-3
2025-02-27 14:56:39,267 - distributed.worker - INFO -          dashboard at:          172.26.1.16:39721
2025-02-27 14:56:39,267 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,267 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,267 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,267 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,267 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-0irugr7q
2025-02-27 14:56:39,267 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,302 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:43071
2025-02-27 14:56:39,302 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:43071
2025-02-27 14:56:39,302 - distributed.worker - INFO -           Worker name:           SLURMCluster-5-2
2025-02-27 14:56:39,302 - distributed.worker - INFO -          dashboard at:          172.26.1.16:42793
2025-02-27 14:56:39,302 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,302 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,302 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,302 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,302 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-btg94un7
2025-02-27 14:56:39,302 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,667 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,668 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,668 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,668 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,669 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,669 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,671 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,680 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,705 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,705 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,705 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,706 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,755 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,755 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,755 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,765 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,782 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,783 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,783 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,792 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,895 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,896 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,896 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,899 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,704 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:01,467 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.75s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:13,728 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.50s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:20,761 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.39s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:26,228 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.84s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:33,408 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.14s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:42,919 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.79s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:52,920 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.62s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,854 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50624 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,875 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,875 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:43071. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,855 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50602 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,879 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,880 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:36467. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,852 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50544 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,883 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,884 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:46639. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50502 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,886 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,887 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:36055. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50618 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,888 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,889 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:35233. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50596 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,891 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,895 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:46243. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,913 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:46849'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,914 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,917 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:45119'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,917 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,919 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:43189'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,920 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,922 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:38893'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,922 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,945 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,950 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:39481'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,950 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,953 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:37517'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,954 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,954 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,956 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,959 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,979 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,992 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,988 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,996 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,996 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,002 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,008 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:17,132 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:37517'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,132 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:37517' closed.
2025-02-27 15:05:17,660 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:46849'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,660 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:46849' closed.
2025-02-27 15:05:17,676 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:39481'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,676 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:39481' closed.
2025-02-27 15:05:17,678 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:38893'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,678 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:38893' closed.
2025-02-27 15:05:17,680 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:43189'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,680 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:43189' closed.
2025-02-27 15:05:17,711 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:45119'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,712 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:45119' closed.
2025-02-27 15:05:17,713 - distributed.dask_worker - INFO - End worker
