2025-02-27 14:56:37,127 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:41247'
2025-02-27 14:56:37,131 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:45723'
2025-02-27 14:56:37,133 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:33919'
2025-02-27 14:56:37,139 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:34463'
2025-02-27 14:56:37,143 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:40563'
2025-02-27 14:56:37,145 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:38279'
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:34667
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:34201
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:36629
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:34667
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:34201
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-4-3
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:36629
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-4-0
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:43347
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-4-1
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:38819
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:43801
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-9d0jhxaw
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-4e2wo3x9
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-6rocq830
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:37217
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:37217
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-4-2
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:32915
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,217 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-xu7w2gl0
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:41189
2025-02-27 14:56:38,217 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:41189
2025-02-27 14:56:38,217 - distributed.worker - INFO -           Worker name:           SLURMCluster-4-4
2025-02-27 14:56:38,217 - distributed.worker - INFO -          dashboard at:           172.26.1.1:40727
2025-02-27 14:56:38,217 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,218 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,218 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-x8zvef1k
2025-02-27 14:56:38,218 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,220 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:35879
2025-02-27 14:56:38,220 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:35879
2025-02-27 14:56:38,220 - distributed.worker - INFO -           Worker name:           SLURMCluster-4-5
2025-02-27 14:56:38,220 - distributed.worker - INFO -          dashboard at:           172.26.1.1:39645
2025-02-27 14:56:38,220 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,220 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,220 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,220 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,221 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-is574khp
2025-02-27 14:56:38,221 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,083 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,084 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,084 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,084 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,085 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,085 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,085 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,086 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,086 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,086 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,086 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,087 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,088 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,089 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,089 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,089 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,098 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,099 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,099 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,099 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,100 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,100 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,100 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,101 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,706 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,711 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:01,818 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.11s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:11,763 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.03s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:14,924 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.40s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:15,228 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.46s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:19,886 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.74s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:23,551 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.66s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:25,501 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.90s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:31,770 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:32,963 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:41,722 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.24s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:41,925 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.96s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:45,132 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.99s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:48,480 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.49s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:34667. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:37217. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:41189. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:36629. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:35879. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,851 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,852 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:34201. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,849 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53766 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53818 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53730 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:34463'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,858 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:40563'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:38279'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53812 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,853 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53732 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,862 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:45723'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,862 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,862 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:41247'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,862 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53778 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,864 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:33919'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,864 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,875 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,878 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,881 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,883 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,886 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,896 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,887 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,887 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,887 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,888 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,898 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,931 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:45723'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:45723' closed.
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:41247'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:41247' closed.
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:33919'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:33919' closed.
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:34463'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:34463' closed.
2025-02-27 15:05:16,932 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:38279'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,933 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:38279' closed.
2025-02-27 15:05:16,933 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:40563'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,933 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:40563' closed.
2025-02-27 15:05:16,933 - distributed.dask_worker - INFO - End worker
