2025-02-27 14:56:37,264 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:34955'
2025-02-27 14:56:37,269 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:38883'
2025-02-27 14:56:37,275 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:41305'
2025-02-27 14:56:37,277 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:43061'
2025-02-27 14:56:37,292 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:39459'
2025-02-27 14:56:37,305 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:33455'
2025-02-27 14:56:37,861 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-3nhn_7vo', purging
2025-02-27 14:56:37,863 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-tu15y83l', purging
2025-02-27 14:56:37,864 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-ullhwkdp', purging
2025-02-27 14:56:37,864 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-u4on9hbh', purging
2025-02-27 14:56:37,866 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-gkannv2d', purging
2025-02-27 14:56:37,867 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-spdm_96e', purging
2025-02-27 14:56:37,867 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-_p809gmz', purging
2025-02-27 14:56:37,868 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-3u8g17uk', purging
2025-02-27 14:56:37,868 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-mpwm292n', purging
2025-02-27 14:56:37,869 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-spa3wfy6', purging
2025-02-27 14:56:37,869 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-itdz0b31', purging
2025-02-27 14:56:37,869 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-f2wqmud1', purging
2025-02-27 14:56:37,870 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-uv7wzp5u', purging
2025-02-27 14:56:37,870 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-ku9r59sl', purging
2025-02-27 14:56:37,871 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-k1d7z31_', purging
2025-02-27 14:56:37,872 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-aptape8y', purging
2025-02-27 14:56:37,872 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-b5c6dvfj', purging
2025-02-27 14:56:37,872 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-zobw27_z', purging
2025-02-27 14:56:38,860 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:40963
2025-02-27 14:56:38,861 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:40963
2025-02-27 14:56:38,861 - distributed.worker - INFO -           Worker name:           SLURMCluster-9-1
2025-02-27 14:56:38,861 - distributed.worker - INFO -          dashboard at:          172.26.1.15:42485
2025-02-27 14:56:38,861 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,861 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,861 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,861 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,861 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-lasqd69w
2025-02-27 14:56:38,861 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,862 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:45589
2025-02-27 14:56:38,863 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:45589
2025-02-27 14:56:38,863 - distributed.worker - INFO -           Worker name:           SLURMCluster-9-3
2025-02-27 14:56:38,863 - distributed.worker - INFO -          dashboard at:          172.26.1.15:42645
2025-02-27 14:56:38,863 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,863 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,863 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,863 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,863 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-52jg0d6h
2025-02-27 14:56:38,863 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,864 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:45703
2025-02-27 14:56:38,865 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:36171
2025-02-27 14:56:38,866 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:46249
2025-02-27 14:56:38,893 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:46249
2025-02-27 14:56:38,893 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:45703
2025-02-27 14:56:38,889 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:44783
2025-02-27 14:56:38,893 - distributed.worker - INFO -           Worker name:           SLURMCluster-9-4
2025-02-27 14:56:38,893 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:36171
2025-02-27 14:56:38,894 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:44783
2025-02-27 14:56:38,894 - distributed.worker - INFO -           Worker name:           SLURMCluster-9-5
2025-02-27 14:56:38,894 - distributed.worker - INFO -           Worker name:           SLURMCluster-9-0
2025-02-27 14:56:38,894 - distributed.worker - INFO -           Worker name:           SLURMCluster-9-2
2025-02-27 14:56:38,894 - distributed.worker - INFO -          dashboard at:          172.26.1.15:38375
2025-02-27 14:56:38,894 - distributed.worker - INFO -          dashboard at:          172.26.1.15:42597
2025-02-27 14:56:38,894 - distributed.worker - INFO -          dashboard at:          172.26.1.15:33571
2025-02-27 14:56:38,894 - distributed.worker - INFO -          dashboard at:          172.26.1.15:41111
2025-02-27 14:56:38,894 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,894 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,894 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,894 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,894 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,894 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,894 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,894 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-o_b9ku83
2025-02-27 14:56:38,894 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,894 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,894 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,894 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,894 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-faz62rcz
2025-02-27 14:56:38,894 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,894 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,894 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,895 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,894 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,895 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-8czop9mf
2025-02-27 14:56:38,895 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,895 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,895 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,895 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-ilgi2nnk
2025-02-27 14:56:38,895 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,713 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,714 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,714 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,714 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,715 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,715 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,715 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,715 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,716 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,716 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,716 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,716 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,716 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,718 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,718 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,718 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,718 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,719 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,719 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,719 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,719 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,727 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,727 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,731 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,705 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.21s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:00,259 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.55s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:19,910 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.26s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:24,676 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.54s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:26,436 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:29,595 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:40,655 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:45,036 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:48,067 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.73s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,848 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55098 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55084 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,848 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55104 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55114 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,860 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,860 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,861 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:36171. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,861 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:46249. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,861 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:45589. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,862 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:45703. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55126 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,863 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:34955'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,863 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:44783. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,868 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:33455'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,868 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:39459'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,868 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,869 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:41305'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55112 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,870 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:43061'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,869 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,870 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:40963. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,870 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,872 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,872 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,879 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:38883'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,891 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,892 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,894 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,894 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,895 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,897 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,920 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,897 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,897 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,943 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,936 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:39459'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,937 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:39459' closed.
2025-02-27 15:05:16,937 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:33455'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,937 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:33455' closed.
2025-02-27 15:05:17,234 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:34955'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,235 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:34955' closed.
2025-02-27 15:05:17,261 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:41305'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,261 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:41305' closed.
2025-02-27 15:05:17,262 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:43061'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,262 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:43061' closed.
2025-02-27 15:05:17,292 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:38883'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,292 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:38883' closed.
2025-02-27 15:05:17,293 - distributed.dask_worker - INFO - End worker
