2025-02-27 14:56:37,427 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:35981'
2025-02-27 14:56:37,491 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:37849'
2025-02-27 14:56:37,527 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:35265'
2025-02-27 14:56:37,563 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:33389'
2025-02-27 14:56:37,599 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:38413'
2025-02-27 14:56:37,637 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.15:33093'
2025-02-27 14:56:39,696 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:38185
2025-02-27 14:56:39,696 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:38185
2025-02-27 14:56:39,696 - distributed.worker - INFO -           Worker name:           SLURMCluster-3-2
2025-02-27 14:56:39,696 - distributed.worker - INFO -          dashboard at:          172.26.1.15:40217
2025-02-27 14:56:39,696 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,696 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,696 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,696 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,696 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-1uy4uvoo
2025-02-27 14:56:39,696 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,706 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:36723
2025-02-27 14:56:39,707 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:36723
2025-02-27 14:56:39,707 - distributed.worker - INFO -           Worker name:           SLURMCluster-3-1
2025-02-27 14:56:39,707 - distributed.worker - INFO -          dashboard at:          172.26.1.15:33081
2025-02-27 14:56:39,707 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,707 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,707 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,707 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,707 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-4eu7lntz
2025-02-27 14:56:39,707 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,922 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:44119
2025-02-27 14:56:39,923 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:44119
2025-02-27 14:56:39,923 - distributed.worker - INFO -           Worker name:           SLURMCluster-3-0
2025-02-27 14:56:39,923 - distributed.worker - INFO -          dashboard at:          172.26.1.15:38753
2025-02-27 14:56:39,923 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,923 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,923 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,923 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,923 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-tr4yexij
2025-02-27 14:56:39,923 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,972 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:43081
2025-02-27 14:56:39,973 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:43081
2025-02-27 14:56:39,973 - distributed.worker - INFO -           Worker name:           SLURMCluster-3-3
2025-02-27 14:56:39,973 - distributed.worker - INFO -          dashboard at:          172.26.1.15:33077
2025-02-27 14:56:39,973 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,973 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,973 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,973 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,973 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-8gxb6zdy
2025-02-27 14:56:39,973 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,024 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:38785
2025-02-27 14:56:40,024 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:38785
2025-02-27 14:56:40,024 - distributed.worker - INFO -           Worker name:           SLURMCluster-3-5
2025-02-27 14:56:40,024 - distributed.worker - INFO -          dashboard at:          172.26.1.15:36495
2025-02-27 14:56:40,024 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,024 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,025 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,025 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,025 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-9ppg688c
2025-02-27 14:56:40,025 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,064 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.15:44525
2025-02-27 14:56:40,064 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.15:44525
2025-02-27 14:56:40,064 - distributed.worker - INFO -           Worker name:           SLURMCluster-3-4
2025-02-27 14:56:40,064 - distributed.worker - INFO -          dashboard at:          172.26.1.15:35177
2025-02-27 14:56:40,064 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,064 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,064 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:40,064 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:40,064 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-7sjgqy9y
2025-02-27 14:56:40,064 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,407 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,407 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,407 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,419 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,419 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,419 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,422 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,435 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,650 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,650 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,651 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,657 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,658 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,658 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,659 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,667 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,716 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,717 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,717 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,731 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:40,813 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:40,814 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:40,814 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:40,823 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,706 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,707 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.66s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,709 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,710 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:15,794 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.41s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:20,056 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.06s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:22,043 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.43s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:22,762 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:44,665 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.17s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55226 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55134 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55160 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,858 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,859 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:44525. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,859 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,860 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:38185. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:44119. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55158 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55196 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,862 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:38413'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,862 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,862 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:35265'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:43081. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:35981'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,862 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,863 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:38785. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.15:55142 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,866 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,867 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.15:36723. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,867 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:33093'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,868 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:33389'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,869 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,870 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,871 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.15:37849'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,873 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,876 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,899 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,904 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,904 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,914 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,917 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,920 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,936 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,936 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,947 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,947 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,957 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,957 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:17,418 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:35265'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,419 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:35265' closed.
2025-02-27 15:05:17,426 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:33093'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,426 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:33093' closed.
2025-02-27 15:05:17,512 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:33389'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,512 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:33389' closed.
2025-02-27 15:05:17,516 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:38413'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,516 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:38413' closed.
2025-02-27 15:05:17,556 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:35981'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,556 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:35981' closed.
2025-02-27 15:05:17,587 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.15:37849'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,588 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.15:37849' closed.
2025-02-27 15:05:17,589 - distributed.dask_worker - INFO - End worker
