2025-02-27 14:56:37,127 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:42963'
2025-02-27 14:56:37,131 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:42779'
2025-02-27 14:56:37,133 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:41981'
2025-02-27 14:56:37,136 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:42969'
2025-02-27 14:56:37,141 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:35753'
2025-02-27 14:56:37,144 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:36027'
2025-02-27 14:56:37,676 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-41h4e_14', purging
2025-02-27 14:56:37,677 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-_e_nwf0w', purging
2025-02-27 14:56:37,678 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-5rkpv4sv', purging
2025-02-27 14:56:37,678 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-hayvv3r8', purging
2025-02-27 14:56:37,678 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-dfon5r1c', purging
2025-02-27 14:56:37,678 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-8yxa3hkb', purging
2025-02-27 14:56:37,679 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-2lnfzqek', purging
2025-02-27 14:56:37,679 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-f1ca3e0y', purging
2025-02-27 14:56:37,679 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-g6oluph7', purging
2025-02-27 14:56:37,679 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-xbxyuyuc', purging
2025-02-27 14:56:37,679 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-tg70cdqv', purging
2025-02-27 14:56:37,680 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-qwnz4ftl', purging
2025-02-27 14:56:37,680 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-8brel8vh', purging
2025-02-27 14:56:37,680 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-9nv5bsn4', purging
2025-02-27 14:56:37,681 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-y50_h_hk', purging
2025-02-27 14:56:37,681 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-3s5ko1a0', purging
2025-02-27 14:56:37,681 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-92etfhp1', purging
2025-02-27 14:56:37,681 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-ii48zsdi', purging
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:44919
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:44919
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-6-3
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:45063
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:38987
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:46121
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:35175
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:38987
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-eweo20yb
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-6-1
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:46121
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:35175
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:46149
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-6-0
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-6-4
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:37877
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:32917
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:39889
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:37877
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-6-5
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:33973
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-nync05m4
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-x9ll04qs
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-c38sa81m
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-cqvdlhh1
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,219 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:41191
2025-02-27 14:56:38,220 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:41191
2025-02-27 14:56:38,220 - distributed.worker - INFO -           Worker name:           SLURMCluster-6-2
2025-02-27 14:56:38,220 - distributed.worker - INFO -          dashboard at:           172.26.1.1:42575
2025-02-27 14:56:38,220 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,220 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,220 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,220 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,221 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-1b3e4b2_
2025-02-27 14:56:38,221 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,089 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,090 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,090 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,090 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,092 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,092 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,092 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,093 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,096 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,096 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,096 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,097 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,097 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,097 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,097 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,098 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,098 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,098 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,098 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,098 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,099 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,099 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,099 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,100 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:54,825 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.59s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,708 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,712 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:01,436 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.07s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:07,902 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.35s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:11,762 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:12,769 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.48s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:20,268 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.46s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:47,994 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.30s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:44919. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:35175. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:46121. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:38987. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:37877. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,847 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:41191. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53840 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53794 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53788 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,856 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:42779'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:36027'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:42969'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53792 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53836 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,858 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:42963'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:35753'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,849 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53802 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,860 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:41981'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,884 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,893 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,896 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,899 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,900 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,902 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,918 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,918 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,918 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,918 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,919 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,918 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:41981'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,918 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:41981' closed.
2025-02-27 15:05:17,050 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:42969'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,051 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:42969' closed.
2025-02-27 15:05:17,066 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:42963'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,067 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:42963' closed.
2025-02-27 15:05:17,245 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:42779'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,245 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:42779' closed.
2025-02-27 15:05:17,369 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:35753'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,369 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:35753' closed.
2025-02-27 15:05:17,423 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:36027'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,424 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:36027' closed.
2025-02-27 15:05:17,424 - distributed.dask_worker - INFO - End worker
