2025-02-27 14:56:37,116 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.2:39441'
2025-02-27 14:56:37,120 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.2:32873'
2025-02-27 14:56:37,122 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.2:40545'
2025-02-27 14:56:37,131 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.2:44833'
2025-02-27 14:56:37,134 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.2:43723'
2025-02-27 14:56:37,141 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.2:39813'
2025-02-27 14:56:37,658 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-4iu4zjk_', purging
2025-02-27 14:56:37,658 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-g09c6znb', purging
2025-02-27 14:56:37,659 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-30sblyc1', purging
2025-02-27 14:56:37,659 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-6vwb2iws', purging
2025-02-27 14:56:37,659 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-qvw9gxc9', purging
2025-02-27 14:56:37,660 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-qjxltmaf', purging
2025-02-27 14:56:37,660 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-op7woini', purging
2025-02-27 14:56:37,660 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-de8abjso', purging
2025-02-27 14:56:37,660 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-0rl6vevh', purging
2025-02-27 14:56:37,661 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-xsox0f2z', purging
2025-02-27 14:56:37,661 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-dj2d3yt2', purging
2025-02-27 14:56:37,661 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-7m90egg3', purging
2025-02-27 14:56:37,662 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-w_3nty_i', purging
2025-02-27 14:56:37,662 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-dac7ofif', purging
2025-02-27 14:56:37,662 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-cgetp44b', purging
2025-02-27 14:56:37,662 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-wpy6vvk2', purging
2025-02-27 14:56:37,662 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-8hciq50x', purging
2025-02-27 14:56:37,663 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-yb4n08em', purging
2025-02-27 14:56:38,166 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.2:43313
2025-02-27 14:56:38,166 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.2:43353
2025-02-27 14:56:38,166 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.2:43313
2025-02-27 14:56:38,166 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.2:40403
2025-02-27 14:56:38,166 - distributed.worker - INFO -           Worker name:           SLURMCluster-1-4
2025-02-27 14:56:38,166 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.2:40431
2025-02-27 14:56:38,166 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.2:38555
2025-02-27 14:56:38,166 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.2:43353
2025-02-27 14:56:38,167 - distributed.worker - INFO -          dashboard at:           172.26.1.2:45743
2025-02-27 14:56:38,167 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.2:40403
2025-02-27 14:56:38,167 - distributed.worker - INFO -           Worker name:           SLURMCluster-1-3
2025-02-27 14:56:38,167 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.2:38555
2025-02-27 14:56:38,167 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.2:40431
2025-02-27 14:56:38,167 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -           Worker name:           SLURMCluster-1-2
2025-02-27 14:56:38,167 - distributed.worker - INFO -          dashboard at:           172.26.1.2:37541
2025-02-27 14:56:38,167 - distributed.worker - INFO -           Worker name:           SLURMCluster-1-1
2025-02-27 14:56:38,167 - distributed.worker - INFO -           Worker name:           SLURMCluster-1-0
2025-02-27 14:56:38,167 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,167 - distributed.worker - INFO -          dashboard at:           172.26.1.2:41167
2025-02-27 14:56:38,167 - distributed.worker - INFO -          dashboard at:           172.26.1.2:41599
2025-02-27 14:56:38,167 - distributed.worker - INFO -          dashboard at:           172.26.1.2:38855
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.2:42907
2025-02-27 14:56:38,167 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,167 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,167 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.2:42907
2025-02-27 14:56:38,167 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-_qx6irrt
2025-02-27 14:56:38,167 - distributed.worker - INFO -           Worker name:           SLURMCluster-1-5
2025-02-27 14:56:38,167 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,167 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,167 - distributed.worker - INFO -          dashboard at:           172.26.1.2:36067
2025-02-27 14:56:38,167 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,167 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,167 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,167 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,167 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-42n2jpjc
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-5_irsl9p
2025-02-27 14:56:38,167 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-pznxqzd7
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-0cdilhog
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,167 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,167 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,167 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-n49vcqz0
2025-02-27 14:56:38,167 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,006 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,007 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,007 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,007 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,008 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,008 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,008 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,008 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,008 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,009 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,009 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,009 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,010 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,010 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,010 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,010 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,010 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,010 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,010 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,010 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,011 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,011 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,011 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,012 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:54,816 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.28s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,704 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,704 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,705 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.21s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,706 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.21s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,710 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:11,914 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.28s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:29,683 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.50s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:35,140 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.98s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:50,079 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.91s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:51,987 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.91s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:52,519 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,847 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.2:40403. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,849 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.2:43313. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,849 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.2:43353. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,850 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,851 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.2:40431. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,855 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,856 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.2:38555. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,852 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,859 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.2:42907. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.2:52126 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,854 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.2:52136 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,848 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.2:52170 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,859 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.2:52180 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,863 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.2:39441'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,852 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.2:52164 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,869 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,870 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.2:32873'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,871 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.2:39813'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,871 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,871 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,874 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.2:40545'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,875 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,867 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.2:52148 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,876 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.2:44833'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,877 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,880 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.2:43723'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,880 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,898 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,898 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,900 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,900 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,901 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,912 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,913 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,914 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,917 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,917 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,927 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,920 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.2:32873'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,920 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.2:32873' closed.
2025-02-27 15:05:16,920 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.2:44833'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,921 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.2:44833' closed.
2025-02-27 15:05:16,923 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.2:39813'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,923 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.2:39813' closed.
2025-02-27 15:05:17,146 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.2:39441'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,146 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.2:39441' closed.
2025-02-27 15:05:17,163 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.2:43723'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,163 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.2:43723' closed.
2025-02-27 15:05:17,200 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.2:40545'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,200 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.2:40545' closed.
2025-02-27 15:05:17,201 - distributed.dask_worker - INFO - End worker
